using System.Collections.Generic;
using DopplerLab.Models;

namespace DopplerLab.Services
{
    public static class QuizRepository
    {
        public static List<QuizQuestion> GetQuestions()
        {
            return new List<QuizQuestion>
            {
                Q(1, "Basics", "Easy",
                    "عندما تقترب دراجة نارية من مستمع ساكن، ماذا يحدث للتردد المسموع؟",
                    "When a motorcycle approaches a stationary listener, what happens to the heard frequency?",
                    new[] {"يزداد", "ينقص", "يبقى دائما مساويا", "يعتمد فقط على المسافة"},
                    new[] {"It increases", "It decreases", "It is always equal", "It depends only on distance"},
                    0,
                    "الموجات تصل بفواصل زمنية أقصر لأن المصدر يتحرك نحو المستمع.",
                    "Wave crests arrive closer together because the source moves toward the listener."),
                Q(2, "Radial velocity", "Easy",
                    "أي جزء من سرعة المصدر يحدد تغير النغمة في اللحظة نفسها؟",
                    "Which part of source velocity determines the pitch shift at an instant?",
                    new[] {"المركبة الشعاعية", "السرعة الكلية فقط", "المسافة فقط", "لون السيارة"},
                    new[] {"The radial component", "Only total speed", "Only distance", "The motorcycle color"},
                    0,
                    "المركبة على خط المصدر-المستمع هي التي تغير فواصل وصول القمم.",
                    "The component along the source-observer line changes the crest arrival spacing."),
                Q(3, "Tangential", "Medium",
                    "مصدر يتحرك بسرعة كبيرة حول المستمع على دائرة ثابتة. ما التغير اللحظي الأولي في التردد؟",
                    "A source moves quickly around a listener on a fixed circle. What is the first-order instantaneous frequency shift?",
                    new[] {"قريب من الصفر", "أعلى دائما", "أقل دائما", "لا يمكن حسابه"},
                    new[] {"Nearly zero", "Always higher", "Always lower", "Impossible to calculate"},
                    0,
                    "الحركة المماسية لا تغلق المسافة أو تفتحها في تلك اللحظة.",
                    "Tangential motion is not closing or opening the distance at that instant."),
                Q(4, "Loudness", "Easy",
                    "ماذا تغير المسافة مباشرة في نموذج المختبر؟",
                    "What does distance directly change in the lab model?",
                    new[] {"الشدة/العلو", "التردد فقط", "سرعة الصوت", "اتجاه الزمن"},
                    new[] {"Loudness/intensity", "Only frequency", "Speed of sound", "Direction of time"},
                    0,
                    "السعة تقريبا 1/r، بينما النغمة تعتمد على الحركة الشعاعية.",
                    "Amplitude is roughly 1/r, while pitch depends on radial motion."),
                Q(5, "Formula", "Medium",
                    "في المعادلة f' = f(c - v_o·n)/(c - v_s·n)، ماذا يعني n؟",
                    "In f' = f(c - v_o·n)/(c - v_s·n), what is n?",
                    new[] {"متجه وحدة من المصدر إلى المستمع", "سرعة الصوت", "المسافة فقط", "عدد الجبهات المرسومة"},
                    new[] {"A unit vector from source to observer", "The speed of sound", "Only the distance", "The number of drawn wavefronts"},
                    0,
                    "استخدام متجه الوحدة يسمح باستخراج المركبات الشعاعية بالضرب النقطي.",
                    "The unit vector lets the dot product extract radial components."),
                Q(6, "Graphs", "Medium",
                    "في مرور جانبي مستمر، ماذا يحدث عند أقرب نقطة تقريبا؟",
                    "In a smooth off-axis pass-by, what happens near closest approach?",
                    new[] {"السرعة الشعاعية تقترب من الصفر", "يقفز التردد فجأة", "تصبح المسافة لا نهائية", "تتغير سرعة الصوت"},
                    new[] {"Radial velocity approaches zero", "Frequency jumps discontinuously", "Distance becomes infinite", "Sound speed changes"},
                    0,
                    "السرعة الكلية كبيرة، لكن المركبة الشعاعية تمر بسلاسة عبر الصفر.",
                    "Total speed can be large while radial velocity smoothly passes through zero."),
                Q(7, "Two listeners", "Medium",
                    "هل يمكن لمستمعين سماع ترددين مختلفين من المصدر نفسه في اللحظة نفسها؟",
                    "Can two listeners hear different frequencies from the same source at the same moment?",
                    new[] {"نعم، لأن الاتجاهات الشعاعية مختلفة", "لا، التردد واحد للجميع", "فقط إذا تغيرت سرعة الصوت", "فقط إذا كان الصوت مسجلا"},
                    new[] {"Yes, because radial directions differ", "No, frequency is identical for everyone", "Only if sound speed changes", "Only for recorded audio"},
                    0,
                    "كل مستمع له خط رؤية وحركة شعاعية خاصة بهما.",
                    "Each listener has its own source-observer line and radial motion."),
                Q(8, "Observer motion", "Medium",
                    "إذا اقترب المستمع من مصدر ساكن، أي جزء من المعادلة يتغير؟",
                    "If the observer approaches a stationary source, which part of the equation changes?",
                    new[] {"البسط", "المقام فقط", "التردد المنبعث", "لا شيء"},
                    new[] {"The numerator", "Only the denominator", "The emitted frequency", "Nothing"},
                    0,
                    "حركة المستمع تظهر في c - v_o·n.",
                    "Observer motion appears in c - v_o dot n."),
                Q(9, "Police radar", "Medium",
                    "لماذا يظهر عامل 2 في رادار الشرطة أحادي الموقع؟",
                    "Why does a factor of 2 appear in monostatic police radar?",
                    new[] {"لأن الموجة تزاح عند الاستقبال ثم عند الانعكاس", "لأن الصوت أسرع من الضوء", "لأن السيارة لها عجلتان أماميتان", "لأنه متوسط حسابي"},
                    new[] {"The wave is shifted on reception and again on reflection", "Sound is faster than light", "The car has two front wheels", "It is an arithmetic average"},
                    0,
                    "الرادار يقيس موجة كهرومغناطيسية منعكسة، وليس مصدرا صوتيا في الهواء.",
                    "Radar measures a reflected electromagnetic wave, not an air-sound source."),
                Q(10, "Ultrasound", "Medium",
                    "لماذا يصبح انزياح دوبلر الطبي ضعيفا قرب زاوية 90°؟",
                    "Why is medical Doppler shift weak near a 90 degree beam angle?",
                    new[] {"لأن cos(theta) قريب من الصفر", "لأن سرعة الدم تصبح صفرا دائما", "لأن سرعة الصوت في الهواء تستخدم", "لأن التردد لا ينعكس"},
                    new[] {"Because cos(theta) is near zero", "Because blood speed is always zero", "Because air sound speed is used", "Because frequency cannot reflect"},
                    0,
                    "المعادلة تستخدم المركبة على اتجاه الحزمة: 2 f0 v cos(theta)/c.",
                    "The equation uses the beam-direction component: 2 f0 v cos(theta)/c."),
                Q(11, "Astronomy", "Hard",
                    "للسرعات الفلكية الكبيرة، أي نموذج يجب استخدامه للضوء؟",
                    "For large astronomical speeds, which model should be used for light?",
                    new[] {"دوبلر نسبي", "معادلة الصوت في الهواء", "تغير العلو 1/r فقط", "معادلة الموجات في الماء"},
                    new[] {"Relativistic Doppler", "The air-sound equation", "Only 1/r loudness", "A water-wave equation"},
                    0,
                    "الضوء لا يحتاج إلى وسط وتدخل النسبية الخاصة عند السرعات العالية.",
                    "Light needs no medium and special relativity matters at high speed."),
                Q(12, "Numerical", "Hard",
                    "مصدر ساكن يصدر 700 Hz ومستمع يقترب بسرعة 10 m/s في هواء 343 m/s. التردد تقريبا؟",
                    "A stationary 700 Hz source and observer approaching at 10 m/s in 343 m/s air. Approximate observed frequency?",
                    new[] {"720.4 Hz", "679.6 Hz", "700.0 Hz", "767.1 Hz"},
                    new[] {"720.4 Hz", "679.6 Hz", "700.0 Hz", "767.1 Hz"},
                    0,
                    "f' = 700(343+10)/343 = 720.4 Hz تقريبا.",
                    "f' = 700(343+10)/343 = about 720.4 Hz.")
            };
        }

        private static QuizQuestion Q(
            int id,
            string topic,
            string difficulty,
            string textAr,
            string textEn,
            string[] choicesAr,
            string[] choicesEn,
            int correctIndex,
            string explanationAr,
            string explanationEn)
        {
            return new QuizQuestion
            {
                Id = id,
                Topic = topic,
                Difficulty = difficulty,
                TextAr = textAr,
                TextEn = textEn,
                ChoicesAr = new List<string>(choicesAr),
                ChoicesEn = new List<string>(choicesEn),
                CorrectIndex = correctIndex,
                ExplanationAr = explanationAr,
                ExplanationEn = explanationEn
            };
        }
    }
}
